id: P000555
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00KG03666
  title: སྡོམ་གསུམ་རྣམ་བཤད་ཐར་ལམ་གསལ་བའི་མེ་ལོང་
  author: ''
  volumes:
    478f1a91941e4f69acc03bb71616ad16:
      image_group_id: I00KG03743
      title: Volume 1 of sdom gsum rnam bzhad thar lam gsal ba'i me long
      volume_number: 1
      total_pages: 264
      base_file: v001.txt
